/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testConstructor () {
        Quotes testQuote = new Quotes("charles","peanut butter jelly");

        assertEquals("Quote: peanut butter jelly \n- charles", testQuote.toString());
    }

}
