/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args) {

        try { // help from https://attacomsian.com/blog/gson-read-json-file
            Gson gson = new Gson();

            Reader reader = Files.newBufferedReader(Paths.get("src/main/resources/quotes.json"));

            Quotes[] quote = gson.fromJson(reader, Quotes[].class);

            int randomNumber = randomNumber();
            System.out.println( quote[randomNumber] );

            reader.close();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public static int randomNumber () {
        int min = 0;
        int max = 138;
        int random = (int) (Math.random() * (max - min + 1) + min);

        return random;
    }
}
